
server:
  port: 8081

spring:

# Este spring.application.name será recuperado pelo Eureka Clint para registrar este serviço
  application:
    name: 'fornecedor'
    
# JPA DataBase Conf
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: root
    password: root 
    url: jdbc:mysql://localhost:3306/fornecedor?useSSL=false&serverTimezone=UTC
    
# Registrando este serviço no Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true    
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/