

# Este spring.application.name será recuperado pelo Eureka Clint para registrar este serviço
spring:  application:    name: 'loja'
    
# Registrando este serviço no Eureka
eureka:  client:    register-with-eureka: true
    fetch-registry: true        serviceUrl:
      defaultZone: http://localhost:8761/eureka/