
server:
  port: 8888

# spring.profiles.active -> Configurando para acessar as configurações dentro do file system
spring:  profiles:    active: native
  cloud:
    config:
      server:
        native:
          search-locations: C:/microservice-repo

